// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-07AZhK_Z9EyiEgD2DpnJuus10JSG3zE',
    appId: '1:209000338259:web:c3289c82977113d6a087a6',
    messagingSenderId: '209000338259',
    projectId: 'booking-app-86dc6',
    authDomain: 'booking-app-86dc6.firebaseapp.com',
    storageBucket: 'booking-app-86dc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJG7_ZQ_KjL4cAFSAK7sbhWxZM8UvAP_M',
    appId: '1:209000338259:android:24a52d479314f15ca087a6',
    messagingSenderId: '209000338259',
    projectId: 'booking-app-86dc6',
    storageBucket: 'booking-app-86dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0k3oN9QIR56qzsxUWekINdJcETXgXSM',
    appId: '1:209000338259:ios:043dc36a48a0736ea087a6',
    messagingSenderId: '209000338259',
    projectId: 'booking-app-86dc6',
    storageBucket: 'booking-app-86dc6.appspot.com',
    iosBundleId: 'com.example.chatGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc0k3oN9QIR56qzsxUWekINdJcETXgXSM',
    appId: '1:209000338259:ios:043dc36a48a0736ea087a6',
    messagingSenderId: '209000338259',
    projectId: 'booking-app-86dc6',
    storageBucket: 'booking-app-86dc6.appspot.com',
    iosBundleId: 'com.example.chatGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-07AZhK_Z9EyiEgD2DpnJuus10JSG3zE',
    appId: '1:209000338259:web:e9dd77a3ab293629a087a6',
    messagingSenderId: '209000338259',
    projectId: 'booking-app-86dc6',
    authDomain: 'booking-app-86dc6.firebaseapp.com',
    storageBucket: 'booking-app-86dc6.appspot.com',
  );
}
